@startuml

title __PROJEKT's Class Diagram__\n

  namespace jovic.dragan.pj2.Interfaces {
    interface jovic.dragan.pj2.Interfaces.Firefighter {
    }
  }
  

  namespace jovic.dragan.pj2.Interfaces {
    abstract class jovic.dragan.pj2.Interfaces.IPreferences {
    }
  }
  

  namespace jovic.dragan.pj2.Interfaces {
    interface jovic.dragan.pj2.Interfaces.Military {
    }
  }
  

  namespace jovic.dragan.pj2.Interfaces {
    interface jovic.dragan.pj2.Interfaces.PassengerCarrier {
    }
  }
  

  namespace jovic.dragan.pj2.Interfaces {
    interface jovic.dragan.pj2.Interfaces.Transporter {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.Aeroplane {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.Aerospace {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.AerospaceObject {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.Aircraft {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.AntiHailRocket {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.BomberPlane {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.FighterPlane {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.FirefighterHelicopter {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.FirefighterPlane {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.Helicopter {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.MilitaryAircraft {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.MilitaryPlane {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.MilitaryRocket {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.PassengerHelicopter {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.PassengerPlane {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.Rocket {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.TransportHelicopter {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.TransportPlane {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    abstract class jovic.dragan.pj2.aerospace.UnmannedAircraft {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    class jovic.dragan.pj2.aerospace.UpdatingTask {
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    namespace equipment {
      class jovic.dragan.pj2.aerospace.equipment.Cargo {
      }
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    namespace equipment {
      class jovic.dragan.pj2.aerospace.equipment.Weapon {
      }
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    namespace generators {
      class jovic.dragan.pj2.aerospace.generators.RandomPlaneGenerator {
      }
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    namespace generators {
      class jovic.dragan.pj2.aerospace.generators.Spawner {
      }
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    namespace generators {
      class jovic.dragan.pj2.aerospace.generators.SpawningRunnable {
      }
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    namespace handlers {
      class jovic.dragan.pj2.aerospace.handlers.CollisionHandler {
      }
    }
  }
  

  namespace jovic.dragan.pj2.aerospace {
    namespace handlers {
      class jovic.dragan.pj2.aerospace.handlers.InvasionHandler {
      }
    }
  }
  

  namespace jovic.dragan.pj2.logger {
    class jovic.dragan.pj2.logger.GenericLogger {
    }
  }
  

  namespace jovic.dragan.pj2.personel {
    class jovic.dragan.pj2.personel.Passenger {
    }
  }
  

  namespace jovic.dragan.pj2.personel {
    class jovic.dragan.pj2.personel.Person {
    }
  }
  

  namespace jovic.dragan.pj2.personel {
    class jovic.dragan.pj2.personel.Pilot {
    }
  }
  

  namespace jovic.dragan.pj2.personel {
    namespace belongings {
      class jovic.dragan.pj2.personel.belongings.FlyingLicence {
      }
    }
  }
  

  namespace jovic.dragan.pj2.personel {
    namespace belongings {
      class jovic.dragan.pj2.personel.belongings.Passport {
      }
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.Constants {
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.GenericPreferences {
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.ModelPreferences {
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.PreferenceWatcher {
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.PreferencesHelper {
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.RadarPreferences {
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.SimulatorPreferences {
    }
  }
  

  namespace jovic.dragan.pj2.preferences {
    class jovic.dragan.pj2.preferences.WeaponPreferences {
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    class jovic.dragan.pj2.radar.ObjectInfo {
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    class jovic.dragan.pj2.radar.Radar {
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    class jovic.dragan.pj2.radar.RadarExporter {
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    namespace collisions {
      class jovic.dragan.pj2.radar.collisions.CollisionChecker {
      }
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    namespace collisions {
      class jovic.dragan.pj2.radar.collisions.CollisionInfo {
      }
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    namespace collisions {
      class jovic.dragan.pj2.radar.collisions.CollisionLogger {
      }
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    namespace collisions {
      class jovic.dragan.pj2.radar.collisions.TextCollisionInfo {
      }
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    namespace invasions {
      class jovic.dragan.pj2.radar.invasions.InvasionsChecker {
      }
    }
  }
  

  namespace jovic.dragan.pj2.radar {
    namespace invasions {
      class jovic.dragan.pj2.radar.invasions.InvasionsLogger {
      }
    }
  }
  

  namespace jovic.dragan.pj2.simulator {
    class jovic.dragan.pj2.simulator.Simulator {
    }
  }
  

  namespace jovic.dragan.pj2.util {
    enum Direction {
    }
  }
  

  namespace jovic.dragan.pj2.util {
    class jovic.dragan.pj2.util.Pair {
    }
  }
  

  namespace jovic.dragan.pj2.util {
    class jovic.dragan.pj2.util.Util {
    }
  }
  

  namespace jovic.dragan.pj2.util {
    class jovic.dragan.pj2.util.Vector2D {
    }
  }
  

  namespace jovic.dragan.pj2.util {
    class jovic.dragan.pj2.util.Vector3D {
    }
  }
  

  namespace jovic.dragan.pj2.util {
    class jovic.dragan.pj2.util.Watcher {
    }
  }
  

  jovic.dragan.pj2.aerospace.Aeroplane .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.Aeroplane -up-|> jovic.dragan.pj2.aerospace.Aircraft
  jovic.dragan.pj2.aerospace.Aerospace o-- jovic.dragan.pj2.util.Watcher : collisionWatcher
  jovic.dragan.pj2.aerospace.Aerospace o-- jovic.dragan.pj2.util.Watcher : invasionWatcher
  jovic.dragan.pj2.aerospace.Aerospace o-- jovic.dragan.pj2.preferences.SimulatorPreferences : preferences
  jovic.dragan.pj2.aerospace.Aerospace o-- jovic.dragan.pj2.aerospace.generators.Spawner : spawner
  jovic.dragan.pj2.aerospace.Aerospace o-- jovic.dragan.pj2.aerospace.UpdatingTask : timerTask
  jovic.dragan.pj2.aerospace.AerospaceObject .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.AerospaceObject o-- jovic.dragan.pj2.util.Direction : direction
  jovic.dragan.pj2.aerospace.AerospaceObject o-- jovic.dragan.pj2.util.Vector2D : directionVector
  jovic.dragan.pj2.aerospace.Aircraft .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.Aircraft -up-|> jovic.dragan.pj2.aerospace.AerospaceObject
  jovic.dragan.pj2.aerospace.AntiHailRocket .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.AntiHailRocket -up-|> jovic.dragan.pj2.aerospace.Rocket
  jovic.dragan.pj2.aerospace.BomberPlane .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.BomberPlane -up-|> jovic.dragan.pj2.aerospace.MilitaryPlane
  jovic.dragan.pj2.aerospace.FighterPlane .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.FighterPlane -up-|> jovic.dragan.pj2.aerospace.MilitaryPlane
  jovic.dragan.pj2.aerospace.FirefighterHelicopter .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.FirefighterHelicopter .up.|> jovic.dragan.pj2.Interfaces.Firefighter
  jovic.dragan.pj2.aerospace.FirefighterHelicopter -up-|> jovic.dragan.pj2.aerospace.Helicopter
  jovic.dragan.pj2.aerospace.FirefighterPlane .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.FirefighterPlane .up.|> jovic.dragan.pj2.Interfaces.Firefighter
  jovic.dragan.pj2.aerospace.FirefighterPlane -up-|> jovic.dragan.pj2.aerospace.Aeroplane
  jovic.dragan.pj2.aerospace.Helicopter .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.Helicopter -up-|> jovic.dragan.pj2.aerospace.Aircraft
  jovic.dragan.pj2.aerospace.MilitaryAircraft .up.|> jovic.dragan.pj2.Interfaces.Military
  jovic.dragan.pj2.aerospace.MilitaryAircraft -up-|> jovic.dragan.pj2.aerospace.Aircraft
  jovic.dragan.pj2.aerospace.MilitaryPlane .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.MilitaryPlane -up-|> jovic.dragan.pj2.aerospace.MilitaryAircraft
  jovic.dragan.pj2.aerospace.MilitaryRocket .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.MilitaryRocket .up.|> jovic.dragan.pj2.Interfaces.Military
  jovic.dragan.pj2.aerospace.MilitaryRocket -up-|> jovic.dragan.pj2.aerospace.Rocket
  jovic.dragan.pj2.aerospace.PassengerHelicopter .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.PassengerHelicopter -up-|> jovic.dragan.pj2.aerospace.Helicopter
  jovic.dragan.pj2.aerospace.PassengerPlane .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.PassengerPlane .up.|> jovic.dragan.pj2.Interfaces.PassengerCarrier
  jovic.dragan.pj2.aerospace.PassengerPlane -up-|> jovic.dragan.pj2.aerospace.Aeroplane
  jovic.dragan.pj2.aerospace.Rocket .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.Rocket -up-|> jovic.dragan.pj2.aerospace.AerospaceObject
  jovic.dragan.pj2.aerospace.TransportHelicopter .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.TransportHelicopter -up-|> jovic.dragan.pj2.aerospace.Helicopter
  jovic.dragan.pj2.aerospace.TransportPlane .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.TransportPlane .up.|> jovic.dragan.pj2.Interfaces.Transporter
  jovic.dragan.pj2.aerospace.TransportPlane -up-|> jovic.dragan.pj2.aerospace.Aeroplane
  jovic.dragan.pj2.aerospace.TransportPlane o-- jovic.dragan.pj2.aerospace.equipment.Cargo : cargo
  jovic.dragan.pj2.aerospace.UnmannedAircraft .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.UnmannedAircraft -up-|> jovic.dragan.pj2.aerospace.Aircraft
  jovic.dragan.pj2.aerospace.UpdatingTask -up-|> java.util.TimerTask
  jovic.dragan.pj2.aerospace.UpdatingTask o-- jovic.dragan.pj2.radar.RadarExporter : exporter
  jovic.dragan.pj2.aerospace.UpdatingTask o-- jovic.dragan.pj2.preferences.SimulatorPreferences : preferences
  jovic.dragan.pj2.aerospace.equipment.Cargo .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.equipment.Weapon .up.|> java.io.Serializable
  jovic.dragan.pj2.aerospace.generators.Spawner o-- jovic.dragan.pj2.aerospace.generators.SpawningRunnable : spawningRunnable
  jovic.dragan.pj2.aerospace.generators.SpawningRunnable .up.|> java.lang.Runnable
  jovic.dragan.pj2.aerospace.generators.SpawningRunnable o-- jovic.dragan.pj2.aerospace.Aerospace : aerospace
  jovic.dragan.pj2.aerospace.generators.SpawningRunnable o-- jovic.dragan.pj2.preferences.SimulatorPreferences : preferences
  jovic.dragan.pj2.aerospace.generators.SpawningRunnable o-- jovic.dragan.pj2.aerospace.generators.RandomPlaneGenerator : rpg
  jovic.dragan.pj2.aerospace.handlers.CollisionHandler .up.|> java.util.function.Consumer
  jovic.dragan.pj2.aerospace.handlers.CollisionHandler o-- jovic.dragan.pj2.aerospace.Aerospace : aerospace
  jovic.dragan.pj2.aerospace.handlers.InvasionHandler .up.|> java.util.function.Consumer
  jovic.dragan.pj2.aerospace.handlers.InvasionHandler o-- jovic.dragan.pj2.aerospace.Aerospace : aerospace
  jovic.dragan.pj2.personel.Passenger .up.|> java.io.Serializable
  jovic.dragan.pj2.personel.Passenger -up-|> jovic.dragan.pj2.personel.Person
  jovic.dragan.pj2.personel.Passenger o-- jovic.dragan.pj2.personel.belongings.Passport : passport
  jovic.dragan.pj2.personel.Person .up.|> java.io.Serializable
  jovic.dragan.pj2.personel.Pilot .up.|> java.io.Serializable
  jovic.dragan.pj2.personel.Pilot -up-|> jovic.dragan.pj2.personel.Person
  jovic.dragan.pj2.personel.Pilot o-- jovic.dragan.pj2.personel.belongings.FlyingLicence : licence
  jovic.dragan.pj2.personel.belongings.FlyingLicence .up.|> java.io.Serializable
  jovic.dragan.pj2.personel.belongings.FlyingLicence o-- jovic.dragan.pj2.personel.Pilot : owner
  jovic.dragan.pj2.personel.belongings.Passport .up.|> java.io.Serializable
  jovic.dragan.pj2.personel.belongings.Passport o-- jovic.dragan.pj2.personel.Person : owner
  jovic.dragan.pj2.preferences.GenericPreferences o-- T : preferences
  jovic.dragan.pj2.preferences.ModelPreferences .up.|> java.io.Serializable
  jovic.dragan.pj2.preferences.PreferenceWatcher o-- T : original
  jovic.dragan.pj2.preferences.SimulatorPreferences .up.|> java.io.Serializable
  jovic.dragan.pj2.radar.ObjectInfo .up.|> java.io.Serializable
  jovic.dragan.pj2.radar.ObjectInfo o-- jovic.dragan.pj2.util.Direction : direction
  jovic.dragan.pj2.radar.RadarExporter o-- jovic.dragan.pj2.preferences.RadarPreferences : radarPreferences
  jovic.dragan.pj2.radar.collisions.CollisionChecker .up.|> java.lang.Runnable
  jovic.dragan.pj2.radar.collisions.TextCollisionInfo .up.|> java.io.Serializable
  jovic.dragan.pj2.radar.invasions.InvasionsChecker .up.|> java.lang.Runnable
  jovic.dragan.pj2.util.Pair o-- T1 : first
  jovic.dragan.pj2.util.Pair o-- T2 : second
  jovic.dragan.pj2.util.Vector2D .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
